spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onedaychallenge?serverTimezone=Asia/Seoul
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: e:\\Project\\ascentic_file
